### ISSUE TITLE
能请教下 你这些直播的api都是怎么获取的吗？

### ISSUE THREAD

**Issue by yugai** [xturbofan/Kanzhibo#1]
如题，我最近也在希望写个看直播的软件给自己用。

**Comment by fanturbo** [comment]
@yugai 抓的各个直播app的接口，用feddler和charles都可以。

**Comment by yugai** [comment]
嗯， 我也尝试过。 但是好像有加密值。    请问有没有获取直播流的api？

**Comment by fanturbo** [comment]
没有拿到。。比如说斗鱼，他的不同版本的直播流API都不一样，而且这个版权问题太大，我也没有尝试。

**Comment by yugai** [comment]
斗鱼和熊猫的github上都能找到。  但是虎牙的好像就没有了

**Comment by fanturbo** [comment]
虎牙的没有开放的API，而且因为要兼容原先yy直播的东西，所以api有点乱，我也只是抓了搜索接口，其他的登录验证之类的也都没有抓到。http://dev-bbs.douyutv.com/forum.php  这是斗鱼的开发者平台。
